title: Quant, Investor, LJM
description: Ljm's strategy and research lab
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown